#!/usr/bin/env php
<?php


echo "What you Do: ";
// open command line input user
$handle = fopen ("php://stdin","r");

// use input user and get value from user

$line = fgets($handle);

switch(trim($line)) {


  case 'create':
    echo "\n Enter Name Controller: ";
    $name = fgets($handle);
    echo $name;
    shell_exec("touch ./Controllers/$name" . '.php');
  break;
    exit;
}

if(trim($line) != 'yes'){
    echo "ABORTING!\n";
    exit;
}
echo "\n";
echo "Thank you, continuing...\n";